# Generated by Django 4.2.6 on 2023-10-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='descricpion',
            new_name='descripcion',
        ),
    ]
